version: 0.2

phases:
  install:
    commands:
      - echo "Navigating to the App directory..."
      - cd App
      - echo "Installing dependencies..."
      - npm install
  pre_build:
    commands:
      - echo "Preparing for build..."
  build:
    commands:
      - echo "Running tests..."
      - npm test || echo "Tests not found, continuing build..."
  post_build:
    commands:
      - echo "Build & test phase completed!"
      - echo "Logging in to Docker registry..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin $ECR_REPO_URI
artifacts:
  files:
    - '**/*'
